In [ ]:
from google.colab import drive

drive.mount("/content/drive")

MessageError: Error: credential propagation was unsuccessful

## Formas de importar datos a Google Colab

Hay varias maneras de importar tus datos a un entorno de Google Colab, dependiendo de dónde se encuentre tu base de datos o archivo:

1.  **Montar Google Drive:** Esto te permite acceder a todos tus archivos almacenados en Google Drive directamente desde Colab.
2.  **Subir archivos directamente:** Puedes subir archivos desde tu ordenador al entorno de Colab. Ten en cuenta que estos archivos son temporales y se borrarán cuando termine la sesión de Colab.
3.  **Descargar desde una URL:** Si tus datos están disponibles en línea a través de un enlace (por ejemplo, un archivo CSV, Excel, o una base de datos pública), puedes descargarlos programáticamente.
4.  **Conectarse a una base de datos externa:** Para bases de datos más complejas (como SQL, NoSQL), necesitarás usar las librerías de Python adecuadas para establecer una conexión.

### 1. Montar Google Drive (solución al error previo)

Si te aparece el error `Error: credential propagation was unsuccessful` al intentar montar Google Drive, a menudo puedes solucionarlo volviendo a ejecutar la celda o revisando la ventana emergente de autenticación. Asegúrate de iniciar sesión con la cuenta de Google correcta y conceder los permisos necesarios.

```python
from google.colab import drive
drive.mount('/content/drive')
```

Una vez montado, podrás acceder a tus archivos en `'/content/drive/MyDrive/'`.

In [ ]:
# Para volver a intentar montar Google Drive (si la celda anterior falló)
# from google.colab import drive
# drive.mount('/content/drive')

### 2. Subir archivos directamente

Esta opción es útil para archivos pequeños. Después de ejecutar la celda, se te pedirá que selecciones un archivo de tu ordenador.

In [ ]:
from google.colab import files
import pandas as pd

print("Por favor, sube tu archivo de datos (por ejemplo, .csv, .xlsx):")
uploaded = files.upload()

for fn in uploaded.keys():
  print(f'Archivo subido: {fn}')
  # Para leer un archivo CSV, por ejemplo
  # df = pd.read_csv(io.BytesIO(uploaded[fn]))
  # display(df.head())

# Puedes adaptar esto para leer diferentes tipos de archivos
# import io
# df = pd.read_csv(io.BytesIO(uploaded[list(uploaded.keys())[0]]))
# display(df.head())

Por favor, sube tu archivo de datos (por ejemplo, .csv, .xlsx):

Saving covtype.info to covtype.info
Archivo subido: covtype.info

## Descoberta de Features com Pandas (usando `df_url` como exemplo)

Para um DataFrame, você pode usar os seguintes métodos para entender suas "features":

1.  **`df.info()`**: Fornece um resumo conciso do DataFrame, incluindo o tipo de dados de cada coluna, o número de valores não nulos e o uso de memória. É excelente para verificar tipos de dados e valores ausentes.
2.  **`df.head()`**: Mostra as primeiras 5 linhas do DataFrame, permitindo uma visualização rápida das colunas e dos dados.
3.  **`df.columns`**: Retorna uma lista com os nomes de todas as colunas (features) do DataFrame.
4.  **`df.describe()`**: Gera estatísticas descritivas para as colunas numéricas, como média, desvio padrão, mínimo, máximo e quartis. Útil para entender a distribuição dos dados.
5.  **`df.nunique()`**: Conta o número de valores únicos em cada coluna, útil para identificar colunas categóricas e verificar a cardinalidade.

In [ ]:
import pandas as pd

print("1. Informações gerais do DataFrame (df.info()):")
df_url.info()

print("\n2. Primeiras 5 linhas do DataFrame (df.head()):")
display(df_url.head())

print("\n3. Nomes das colunas (features) (df.columns):")
print(df_url.columns.tolist())

print("\n4. Estatísticas descritivas para colunas numéricas (df.describe()):")
display(df_url.describe())

print("\n5. Contagem de valores únicos por coluna (df.nunique()):")
display(df_url.nunique())

1. Informações gerais do DataFrame (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal length  150 non-null    float64
 1   sepal width   150 non-null    float64
 2   petal length  150 non-null    float64
 3   petal width   150 non-null    float64
 4   class         150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

2. Primeiras 5 linhas do DataFrame (df.head()):

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

3. Nomes das colunas (features) (df.columns):
['sepal length', 'sepal width', 'petal length', 'petal width', 'class']

4. Estatísticas descritivas para colunas numéricas (df.describe()):

       sepal length  sepal width  petal length  petal width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

5. Contagem de valores únicos por coluna (df.nunique()):

sepal length    35
sepal width     23
petal length    43
petal width     22
class            3
dtype: int64

## Analisando o arquivo `covtype.info`

Você carregou um arquivo `covtype.info`. Pelo nome, parece ser um arquivo que contém informações ou metadados sobre o conjunto de dados 'Covertype'. Para entender suas features, precisaríamos ler e interpretar o conteúdo deste arquivo. Ele pode descrever as colunas, seus tipos, unidades, e qualquer pré-processamento necessário para o dataset real 'Covertype'.

Podemos ler o conteúdo deste arquivo e exibi-lo para que você possa ver as informações que ele contém. Se o arquivo 'covtype.info' descreve as colunas de outro arquivo de dados, precisaremos desse outro arquivo para criar um DataFrame e aplicar as técnicas acima.

In [ ]:
# Para ler e exibir o conteúdo do arquivo covtype.info
with open('covtype.info', 'r') as f:
    content = f.read()
print("Conteúdo do arquivo covtype.info:\n")
print(content)

# Se houver um arquivo de dados 'covtype.csv' ou similar, você o carregaria aqui
# Exemplo: df_covtype = pd.read_csv('covtype.csv')
# E então aplicaria df_covtype.info(), df_covtype.head(), etc. para explorar suas features.

Conteúdo do arquivo covtype.info:

The Forest CoverType dataset


1.	Title of Database:

	Forest Covertype data


2.	Sources:

	(a) Original owners of database:
		Remote Sensing and GIS Program
		Department of Forest Sciences
		College of Natural Resources
		Colorado State University
		Fort Collins, CO  80523
		(contact Jock A. Blackard, jblackard 'at' fs.fed.us
		      or Dr. Denis J. Dean, denis.dean 'at' utdallas.edu)

	NOTE:	Reuse of this database is unlimited with retention of
		copyright notice for Jock A. Blackard and Colorado
		State University.

	(b) Donors of database:
		Jock A. Blackard (jblackard 'at' fs.fed.us)
		GIS Coordinator
		USFS - Forest Inventory & Analysis
		Rocky Mountain Research Station
		507 25th Street
		Ogden, UT 84401

		Dr. Denis J. Dean (denis.dean 'at' utdallas.edu)
		Professor
		Program in Geography and Geospatial Sciences
		School of Economic, Political and Policy Sciences
		800 West Campbell Rd
		Richardson, TX  75080-3021

		Dr. Charles W. Anderson (anderson 'at' cs.colostate.edu)
		Associate Professor
		Department of Computer Science
		Colorado State University
		Fort Collins, CO  80523  USA

	(c) Date donated:  August 1998


3.	Past Usage:

	Blackard, Jock A. and Denis J. Dean.  2000.  "Comparative
		Accuracies of Artificial Neural Networks and Discriminant
		Analysis in Predicting Forest Cover Types from Cartographic
		Variables."  Computers and Electronics in Agriculture
		24(3):131-151.

	Blackard, Jock A. and Denis J. Dean.  1998.  "Comparative
		Accuracies of Neural Networks and Discriminant Analysis
		in Predicting Forest Cover Types from Cartographic
		Variables."  Second Southern Forestry GIS Conference.
		University of Georgia.  Athens, GA.  Pages 189-199.

	Blackard, Jock A.  1998.  "Comparison of Neural Networks and
		Discriminant Analysis in Predicting Forest Cover Types."
		Ph.D. dissertation.  Department of Forest Sciences.
		Colorado State University.  Fort Collins, Colorado.
		165 pages.

	Abstract of dissertation:
		Natural resource managers responsible for developing
	ecosystem management strategies require basic descriptive
	information including inventory data for forested lands to
	support their decision-making processes.  However, managers
	generally do not have this type of data for inholdings or
	neighboring lands that are outside their immediate
	jurisdiction.  One method of obtaining this information is
	through the use of predictive models.
		Two predictive models were examined in this study, a
	feedforward neural network model and a more traditional
	statistical model based on discriminant analysis.  The overall
	objectives of this research were to first construct these two
	predictive models, and second to compare and evaluate their
	respective classification accuracies when predicting forest
	cover types in undisturbed forests.
		The study area included four wilderness areas found in
	the Roosevelt National Forest of northern Colorado.  A total
	of twelve cartographic measures were utilized as independent
	variables in the predictive models, while seven major forest
	cover types were used as dependent variables.  Several subsets
	of these variables were examined to determine the best overall
	predictive model.
		For each subset of cartographic variables examined in
	this study, relative classification accuracies indicate the
	neural network approach outperformed the traditional
	discriminant analysis method in predicting forest cover types.
	The final neural network model had a higher absolute
	classification accuracy (70.58%) than the final corresponding
	linear discriminant analysis model(58.38%).  In support of these
	classification results, thirty additional networks with randomly
	selected initial weights were derived.  From these networks, the
	overall mean absolute classification accuracy for the neural
	network method was 70.52%, with a 95% confidence interval of
	70.26% to 70.80%.  Consequently, natural resource managers may
	utilize an alternative method of predicting forest cover types
	that is both superior to the traditional statistical methods and
	adequate to support their decision-making processes for
	developing ecosystem management strategies.


	-- Classification performance
		-- first 11,340 records used for training data subset
		-- next 3,780 records used for validation data subset
		-- last 565,892 records used for testing data subset
		-- 70% Neural Network (backpropagation)
		-- 58% Linear Discriminant Analysis


4.	Relevant Information Paragraph:

	Predicting forest cover type from cartographic variables only
	(no remotely sensed data).  The actual forest cover type for
	a given observation (30 x 30 meter cell) was determined from
	US Forest Service (USFS) Region 2 Resource Information System
	(RIS) data.  Independent variables were derived from data
	originally obtained from US Geological Survey (USGS) and
	USFS data.  Data is in raw form (not scaled) and contains
	binary (0 or 1) columns of data for qualitative independent
	variables (wilderness areas and soil types).

	This study area includes four wilderness areas located in the
	Roosevelt National Forest of northern Colorado.  These areas
	represent forests with minimal human-caused disturbances,
	so that existing forest cover types are more a result of
	ecological processes rather than forest management practices.

	Some background information for these four wilderness areas:
	Neota (area 2) probably has the highest mean elevational value of
	the 4 wilderness areas. Rawah (area 1) and Comanche Peak (area 3)
	would have a lower mean elevational value, while Cache la Poudre
	(area 4) would have the lowest mean elevational value.

	As for primary major tree species in these areas, Neota would have
	spruce/fir (type 1), while Rawah and Comanche Peak would probably
	have lodgepole pine (type 2) as their primary species, followed by
	spruce/fir and aspen (type 5). Cache la Poudre would tend to have
	Ponderosa pine (type 3), Douglas-fir (type 6), and
	cottonwood/willow (type 4).

	The Rawah and Comanche Peak areas would tend to be more typical of
	the overall dataset than either the Neota or Cache la Poudre, due
	to their assortment of tree species and range of predictive
	variable values (elevation, etc.)  Cache la Poudre would probably
	be more unique than the others, due to its relatively low
	elevation range and species composition.


5.	Number of instances (observations):  581,012


6.	Number of Attributes:	12 measures, but 54 columns of data
				(10 quantitative variables, 4 binary
				wilderness areas and 40 binary
				soil type variables)


7.	Attribute information:

Given is the attribute name, attribute type, the measurement unit and
a brief description.  The forest cover type is the classification
problem.  The order of this listing corresponds to the order of
numerals along the rows of the database.

Name                                     Data Type    Measurement                       Description

Elevation                               quantitative    meters                       Elevation in meters
Aspect                                  quantitative    azimuth                      Aspect in degrees azimuth
Slope                                   quantitative    degrees                      Slope in degrees
Horizontal_Distance_To_Hydrology        quantitative    meters                       Horz Dist to nearest surface water features
Vertical_Distance_To_Hydrology          quantitative    meters                       Vert Dist to nearest surface water features
Horizontal_Distance_To_Roadways         quantitative    meters                       Horz Dist to nearest roadway
Hillshade_9am                           quantitative    0 to 255 index               Hillshade index at 9am, summer solstice
Hillshade_Noon                          quantitative    0 to 255 index               Hillshade index at noon, summer soltice
Hillshade_3pm                           quantitative    0 to 255 index               Hillshade index at 3pm, summer solstice
Horizontal_Distance_To_Fire_Points      quantitative    meters                       Horz Dist to nearest wildfire ignition points
Wilderness_Area (4 binary columns)      qualitative     0 (absence) or 1 (presence)  Wilderness area designation
Soil_Type (40 binary columns)           qualitative     0 (absence) or 1 (presence)  Soil Type designation
Cover_Type (7 types)                    integer         1 to 7                       Forest Cover Type designation


Code Designations:

Wilderness Areas:  	1 -- Rawah Wilderness Area
                        2 -- Neota Wilderness Area
                        3 -- Comanche Peak Wilderness Area
                        4 -- Cache la Poudre Wilderness Area

Soil Types:             1 to 40 : based on the USFS Ecological
                        Landtype Units (ELUs) for this study area:

  Study Code USFS ELU Code			Description
	 1	   2702		Cathedral family - Rock outcrop complex, extremely stony.
	 2	   2703		Vanet - Ratake families complex, very stony.
	 3	   2704		Haploborolis - Rock outcrop complex, rubbly.
	 4	   2705		Ratake family - Rock outcrop complex, rubbly.
	 5	   2706		Vanet family - Rock outcrop complex complex, rubbly.
	 6	   2717		Vanet - Wetmore families - Rock outcrop complex, stony.
	 7	   3501		Gothic family.
	 8	   3502		Supervisor - Limber families complex.
	 9	   4201		Troutville family, very stony.
	10	   4703		Bullwark - Catamount families - Rock outcrop complex, rubbly.
	11	   4704		Bullwark - Catamount families - Rock land complex, rubbly.
	12	   4744		Legault family - Rock land complex, stony.
	13	   4758		Catamount family - Rock land - Bullwark family complex, rubbly.
	14	   5101		Pachic Argiborolis - Aquolis complex.
	15	   5151		unspecified in the USFS Soil and ELU Survey.
	16	   6101		Cryaquolis - Cryoborolis complex.
	17	   6102		Gateview family - Cryaquolis complex.
	18	   6731		Rogert family, very stony.
	19	   7101		Typic Cryaquolis - Borohemists complex.
	20	   7102		Typic Cryaquepts - Typic Cryaquolls complex.
	21	   7103		Typic Cryaquolls - Leighcan family, till substratum complex.
	22	   7201		Leighcan family, till substratum, extremely bouldery.
	23	   7202		Leighcan family, till substratum - Typic Cryaquolls complex.
	24	   7700		Leighcan family, extremely stony.
	25	   7701		Leighcan family, warm, extremely stony.
	26	   7702		Granile - Catamount families complex, very stony.
	27	   7709		Leighcan family, warm - Rock outcrop complex, extremely stony.
	28	   7710		Leighcan family - Rock outcrop complex, extremely stony.
	29	   7745		Como - Legault families complex, extremely stony.
	30	   7746		Como family - Rock land - Legault family complex, extremely stony.
	31	   7755		Leighcan - Catamount families complex, extremely stony.
	32	   7756		Catamount family - Rock outcrop - Leighcan family complex, extremely stony.
	33	   7757		Leighcan - Catamount families - Rock outcrop complex, extremely stony.
	34	   7790		Cryorthents - Rock land complex, extremely stony.
	35	   8703		Cryumbrepts - Rock outcrop - Cryaquepts complex.
	36	   8707		Bross family - Rock land - Cryumbrepts complex, extremely stony.
	37	   8708		Rock outcrop - Cryumbrepts - Cryorthents complex, extremely stony.
	38	   8771		Leighcan - Moran families - Cryaquolls complex, extremely stony.
	39	   8772		Moran family - Cryorthents - Leighcan family complex, extremely stony.
	40	   8776		Moran family - Cryorthents - Rock land complex, extremely stony.

        Note:   First digit:  climatic zone             Second digit:  geologic zones
                1.  lower montane dry                   1.  alluvium
                2.  lower montane                       2.  glacial
                3.  montane dry                         3.  shale
                4.  montane                             4.  sandstone
                5.  montane dry and montane             5.  mixed sedimentary
                6.  montane and subalpine               6.  unspecified in the USFS ELU Survey
                7.  subalpine                           7.  igneous and metamorphic
                8.  alpine                              8.  volcanic

        The third and fourth ELU digits are unique to the mapping unit
        and have no special meaning to the climatic or geologic zones.

Forest Cover Type Classes:	1 -- Spruce/Fir
                                2 -- Lodgepole Pine
                                3 -- Ponderosa Pine
                                4 -- Cottonwood/Willow
                                5 -- Aspen
                                6 -- Douglas-fir
                                7 -- Krummholz


8.  Basic Summary Statistics for quantitative variables only
	(whole dataset -- thanks to Phil Rennert for the summary values):

Name                                    Units             Mean   Std Dev
Elevation                               meters          2959.36  279.98
Aspect                                  azimuth          155.65  111.91
Slope                                   degrees           14.10    7.49
Horizontal_Distance_To_Hydrology        meters           269.43  212.55
Vertical_Distance_To_Hydrology          meters            46.42   58.30
Horizontal_Distance_To_Roadways         meters          2350.15 1559.25
Hillshade_9am                           0 to 255 index   212.15   26.77
Hillshade_Noon                          0 to 255 index   223.32   19.77
Hillshade_3pm                           0 to 255 index   142.53   38.27
Horizontal_Distance_To_Fire_Points      meters          1980.29 1324.19


9.	Missing Attribute Values:  None.


10.	Class distribution:

           Number of records of Spruce-Fir:                211840
           Number of records of Lodgepole Pine:            283301
           Number of records of Ponderosa Pine:             35754
           Number of records of Cottonwood/Willow:           2747
           Number of records of Aspen:                       9493
           Number of records of Douglas-fir:                17367
           Number of records of Krummholz:                  20510
           Number of records of other:                          0

           Total records:                                  581012

=====================================================================
Jock A. Blackard
08/28/1998 -- original text
12/07/1999 -- updated mailing address, citations, background info
		  for study area, added summary statistics.
=====================================================================

In [ ]:
print(df_url['class'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [ ]:
display(df_url['class'].value_counts())

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

**2. Distribuição das classes no dataset Forest CoverType (conforme descrito em `covtype.info`):**

O arquivo `covtype.info` já contém uma seção detalhada sobre a distribuição das classes de cobertura florestal. Abaixo está o trecho relevante extraído do arquivo:

In [ ]:
# Extraindo a seção de distribuição de classes do texto do covtype.info
import re

class_distribution_match = re.search(r'10\.\s*Class distribution:\s*(.*?)(?=\n\n=====================================================================)', content, re.DOTALL)

if class_distribution_match:
    distribution_text = class_distribution_match.group(1)
    print(distribution_text.strip())
else:
    print("Não foi possível extrair a distribuição de classes do arquivo covtype.info automaticamente. Por favor, revise o conteúdo manualmente.")

Number of records of Spruce-Fir:                211840
           Number of records of Lodgepole Pine:            283301
           Number of records of Ponderosa Pine:             35754
           Number of records of Cottonwood/Willow:           2747
           Number of records of Aspen:                       9493
           Number of records of Douglas-fir:                17367
           Number of records of Krummholz:                  20510
           Number of records of other:                          0

           Total records:                                  581012

**2. Para o dataset Forest CoverType (conforme descrito em `covtype.info`):**

O arquivo `covtype.info` lista as classes de tipo de cobertura florestal. Elas são:

In [ ]:
# Extraindo as classes do texto do covtype.info
import re

classes_match = re.search(r'Forest Cover Type Classes:\s*(.*?)(?=\n\n\n8\.\s*Basic Summary Statistics)', content, re.DOTALL)

if classes_match:
    classes_text = classes_match.group(1)
    # Dividir por linhas e remover espaços em branco, depois extrair o texto após '--'
    class_list = [re.sub(r'\s*\d+\s*--', '', line.strip()) for line in classes_text.split('\n') if line.strip()]
    print(class_list)
else:
    print("Não foi possível extrair as classes do arquivo covtype.info automaticamente. Por favor, revise o conteúdo manualmente.")

[' Spruce/Fir', ' Lodgepole Pine', ' Ponderosa Pine', ' Cottonwood/Willow', ' Aspen', ' Douglas-fir', ' Krummholz']

In [ ]:
import pandas as pd
import numpy as np

# Visualizar tamanho da base
print("Dimensões:", df.shape)

# Visualizar primeiras linhas
display(df.head())

# Informações das colunas
df.info()

NameError: name 'df' is not defined

Para realizar a limpeza e pré-processamento, precisamos primeiro carregar o conjunto de dados 'Forest CoverType' real (o arquivo `covtype.csv`) em um DataFrame. Você já carregou o arquivo `covtype.info`, que é a descrição dos dados, mas não os dados em si. Abaixo, vou fornecer o código para você carregar o arquivo `covtype.csv`.

In [ ]:
from google.colab import files
import pandas as pd
import io

print("Por favor, suba o arquivo de dados 'covtype.csv':")
uploaded_covtype = files.upload()

for fn_covtype in uploaded_covtype.keys():
  print(f'Arquivo subido: {fn_covtype}')
  if fn_covtype.endswith('.csv'):
    df_covtype = pd.read_csv(io.BytesIO(uploaded_covtype[fn_covtype]))
    print(f"DataFrame 'df_covtype' carregado com sucesso!")
  else:
    print("Por favor, suba um arquivo .csv.")

Por favor, suba o arquivo de dados 'covtype.csv':

Saving covtype.csv to covtype.csv
Arquivo subido: covtype.csv
DataFrame 'df_covtype' carregado com sucesso!

Agora que o DataFrame `df_covtype` foi carregado, podemos prosseguir com a análise da sua estrutura e a correção da célula anterior.

In [ ]:
import pandas as pd

df = pd.read_csv("covtype.csv")

# Visualizar tamanho da base
print("Dimensões:", df.shape)

# Visualizar primeiras linhas
display(df.head())

# Informações das colunas
df.info()

Dimensões: (247, 55)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Soil_Type_40,Cover_Type
0,The Forest CoverType dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.\tTitle of Database:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,\tForest Covertype data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.\tSources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,\t(a) Original owners of database:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 55 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Elevation                           247 non-null    object
 1   Aspect                              72 non-null     object
 2   Slope                               6 non-null      object
 3   Horizontal_Distance_To_Hydrology    0 non-null      float64
 4   Vertical_Distance_To_Hydrology      0 non-null      float64
 5   Horizontal_Distance_To_Roadways     0 non-null      float64
 6   Hillshade_9am                       0 non-null      float64
 7   Hillshade_Noon                      0 non-null      float64
 8   Hillshade_3pm                       0 non-null      float64
 9   Horizontal_Distance_To_Fire_Points  0 non-null      float64
 10  Wilderness_Area_1                   0 non-null      float64
 11  Wilderness_Area_2                   0 non-null      float64
 12  Wilderness_Area_3                   0 non-null      float64
 13  Wilderness_Area_4                   0 non-null      float64
 14  Soil_Type_1                         0 non-null      float64
 15  Soil_Type_2                         0 non-null      float64
 16  Soil_Type_3                         0 non-null      float64
 17  Soil_Type_4                         0 non-null      float64
 18  Soil_Type_5                         0 non-null      float64
 19  Soil_Type_6                         0 non-null      float64
 20  Soil_Type_7                         0 non-null      float64
 21  Soil_Type_8                         0 non-null      float64
 22  Soil_Type_9                         0 non-null      float64
 23  Soil_Type_10                        0 non-null      float64
 24  Soil_Type_11                        0 non-null      float64
 25  Soil_Type_12                        0 non-null      float64
 26  Soil_Type_13                        0 non-null      float64
 27  Soil_Type_14                        0 non-null      float64
 28  Soil_Type_15                        0 non-null      float64
 29  Soil_Type_16                        0 non-null      float64
 30  Soil_Type_17                        0 non-null      float64
 31  Soil_Type_18                        0 non-null      float64
 32  Soil_Type_19                        0 non-null      float64
 33  Soil_Type_20                        0 non-null      float64
 34  Soil_Type_21                        0 non-null      float64
 35  Soil_Type_22                        0 non-null      float64
 36  Soil_Type_23                        0 non-null      float64
 37  Soil_Type_24                        0 non-null      float64
 38  Soil_Type_25                        0 non-null      float64
 39  Soil_Type_26                        0 non-null      float64
 40  Soil_Type_27                        0 non-null      float64
 41  Soil_Type_28                        0 non-null      float64
 42  Soil_Type_29                        0 non-null      float64
 43  Soil_Type_30                        0 non-null      float64
 44  Soil_Type_31                        0 non-null      float64
 45  Soil_Type_32                        0 non-null      float64
 46  Soil_Type_33                        0 non-null      float64
 47  Soil_Type_34                        0 non-null      float64
 48  Soil_Type_35                        0 non-null      float64
 49  Soil_Type_36                        0 non-null      float64
 50  Soil_Type_37                        0 non-null      float64
 51  Soil_Type_38                        0 non-null      float64
 52  Soil_Type_39                        0 non-null      float64
 53  Soil_Type_40                        0 non-null      float64
 54  Cover_Type                          0 non-null      float64
dtypes: float64(52), object(3)
memory usage: 106.3+ KB

In [ ]:
relatorio = []

for coluna, (minimo, maximo) in limites.items():

    invalidos = (
        (df[coluna] < minimo) |
        (df[coluna] > maximo)
    ).sum()

    relatorio.append({
        "Coluna": coluna,
        "Mínimo permitido": minimo,
        "Máximo permitido": maximo,
        "Mínimo encontrado": df[coluna].min(),
        "Máximo encontrado": df[coluna].max(),
        "Valores inválidos": invalidos
    })

relatorio_df = pd.DataFrame(relatorio)

print(relatorio_df)

NameError: name 'limites' is not defined

In [ ]:
import pandas as pd

df = pd.read_csv("covtype.csv", header=None)

# Quantidade de valores ausentes por coluna
print(df.isnull().sum())

# Total de valores ausentes
print("Total:", df.isnull().sum().sum())

0       0
1     175
2     241
3     247
4     247
5     247
6     247
7     247
8     247
9     247
10    247
11    247
12    247
13    247
14    247
15    247
16    247
17    247
18    247
19    247
20    247
21    247
22    247
23    247
24    247
25    247
26    247
27    247
28    247
29    247
30    247
31    247
32    247
33    247
34    247
35    247
36    247
37    247
38    247
39    247
40    247
41    247
42    247
43    247
44    247
45    247
46    247
47    247
48    247
49    247
50    247
51    247
52    247
53    247
54    247
dtype: int64
Total: 13260

In [ ]:
percentual_nulos = df.isnull().mean() * 100

print(percentual_nulos[percentual_nulos > 0])

1     70.564516
2     97.177419
3     99.596774
4     99.596774
5     99.596774
6     99.596774
7     99.596774
8     99.596774
9     99.596774
10    99.596774
11    99.596774
12    99.596774
13    99.596774
14    99.596774
15    99.596774
16    99.596774
17    99.596774
18    99.596774
19    99.596774
20    99.596774
21    99.596774
22    99.596774
23    99.596774
24    99.596774
25    99.596774
26    99.596774
27    99.596774
28    99.596774
29    99.596774
30    99.596774
31    99.596774
32    99.596774
33    99.596774
34    99.596774
35    99.596774
36    99.596774
37    99.596774
38    99.596774
39    99.596774
40    99.596774
41    99.596774
42    99.596774
43    99.596774
44    99.596774
45    99.596774
46    99.596774
47    99.596774
48    99.596774
49    99.596774
50    99.596774
51    99.596774
52    99.596774
53    99.596774
54    99.596774
dtype: float64

In [ ]:
df_sem_nulos = df.dropna()

print("Antes:", df.shape)
print("Depois:", df_sem_nulos.shape)

Antes: (248, 55)
Depois: (1, 55)

In [ ]:
df_sem_nulos = df.dropna(axis=1)

In [ ]:
df = df.fillna(df.mean(numeric_only=True))

In [ ]:
for coluna in df.select_dtypes(include='number').columns:
    df[coluna] = df[coluna].fillna(df[coluna].median())

In [ ]:
for coluna in df.columns:
    if df[coluna].isnull().any():
        df[coluna] = df[coluna].fillna(df[coluna].mode()[0])

In [ ]:
import pandas as pd

# ---------------------------------------------------------
# 1. Nomes das colunas
# ---------------------------------------------------------

colunas = [
    "Elevation",
    "Aspect",
    "Slope",
    "Horizontal_Distance_To_Hydrology",
    "Vertical_Distance_To_Hydrology",
    "Horizontal_Distance_To_Roadways",
    "Hillshade_9am",
    "Hillshade_Noon",
    "Hillshade_3pm",
    "Horizontal_Distance_To_Fire_Points"
]

# 4 áreas de preservação
colunas += [f"Wilderness_Area_{i}" for i in range(1, 5)]

# 40 tipos de solo
colunas += [f"Soil_Type_{i}" for i in range(1, 41)]

# Variável alvo
colunas += ["Cover_Type"]


# ---------------------------------------------------------
# 2. Carregar os dados
# ---------------------------------------------------------

df = pd.read_csv(
    "covtype.csv",
    header=None,
    names=colunas
)


# ---------------------------------------------------------
# 3. Verificar tamanho dos dados
# ---------------------------------------------------------

print("Dimensões do dataset:")
print(df.shape)

print("\nPrimeiras linhas:")
print(df.head())


# ---------------------------------------------------------
# 4. Verificar valores ausentes
# ---------------------------------------------------------

print("\nValores ausentes por coluna:")
print(df.isnull().sum())

print("\nTotal de valores ausentes:")
print(df.isnull().sum().sum())


# ---------------------------------------------------------
# 5. Tratar valores ausentes
# ---------------------------------------------------------

# Variáveis numéricas
colunas_numericas = [
    "Elevation",
    "Aspect",
    "Slope",
    "Horizontal_Distance_To_Hydrology",
    "Vertical_Distance_To_Hydrology",
    "Horizontal_Distance_To_Roadways",
    "Hillshade_9am",
    "Hillshade_Noon",
    "Hillshade_3pm",
    "Horizontal_Distance_To_Fire_Points"
]

for coluna in colunas_numericas:
    df[coluna] = df[coluna].fillna(df[coluna].median())


# Variáveis binárias
colunas_binarias = (
    [f"Wilderness_Area_{i}" for i in range(1, 5)] +
    [f"Soil_Type_{i}" for i in range(1, 41)]
)

for coluna in colunas_binarias:
    df[coluna] = df[coluna].fillna(df[coluna].mode()[0])


# ---------------------------------------------------------
# 6. Remover registros duplicados
# ---------------------------------------------------------

duplicados_antes = df.duplicated().sum()

df = df.drop_duplicates()

print("\nDuplicados encontrados:", duplicados_antes)
print("Dimensões após remoção:", df.shape)


# ---------------------------------------------------------
# 7. Verificar valores fora das faixas permitidas
# ---------------------------------------------------------

print("\nValores fora das faixas esperadas:")

print("Aspect:",
      ((df["Aspect"] < 0) | (df["Aspect"] > 360)).sum())

print("Slope:",
      ((df["Slope"] < 0) | (df["Slope"] > 90)).sum())

for coluna in ["Hillshade_9am",
               "Hillshade_Noon",
               "Hillshade_3pm"]:

    print(coluna + ":",
          ((df[coluna] < 0) | (df[coluna] > 255)).sum())

print("Cover_Type:",
      ((df["Cover_Type"] < 1) | (df["Cover_Type"] > 7)).sum())


# ---------------------------------------------------------
# 8. Verificar as variáveis binárias
# ---------------------------------------------------------

for coluna in colunas_binarias:
    valores_invalidos = (~df[coluna].isin([0, 1])).sum()

    if valores_invalidos > 0:
        print(
            f"{coluna}: {valores_invalidos} valores inválidos"
        )


# ---------------------------------------------------------
# 9. Apresentar estatísticas dos dados tratados
# ---------------------------------------------------------

print("\nEstatísticas dos dados tratados:")
print(df.describe())


# ---------------------------------------------------------
# 10. Distribuição das classes
# ---------------------------------------------------------

print("\nDistribuição das classes:")
print(df["Cover_Type"].value_counts().sort_index())


# ---------------------------------------------------------
# 11. Percentual das classes
# ---------------------------------------------------------

print("\nPercentual das classes:")
print(
    df["Cover_Type"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(2)
)


# ---------------------------------------------------------
# 12. Mostrar os dados tratados
# ---------------------------------------------------------

print("\nPrimeiras 10 linhas dos dados tratados:")
print(df.head(10))

print("\nÚltimas 10 linhas dos dados tratados:")
print(df.tail(10))


# ---------------------------------------------------------
# 13. Salvar arquivo tratado
# ---------------------------------------------------------

df.to_csv(
    "covtype_tratado.csv",
    index=False
)

print("\nArquivo salvo como: covtype_tratado.csv")

Dimensões do dataset:
(248, 55)

Primeiras linhas:
                      Elevation  Aspect  Slope  \
0                     Elevation  Aspect  Slope
1  The Forest CoverType dataset     NaN    NaN
2        1.\tTitle of Database:     NaN    NaN
3       \tForest Covertype data     NaN    NaN
4                  2.\tSources:     NaN    NaN

   Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology  \
0  Horizontal_Distance_To_Hydrology  Vertical_Distance_To_Hydrology
1                               NaN                             NaN
2                               NaN                             NaN
3                               NaN                             NaN
4                               NaN                             NaN

   Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon  \
0  Horizontal_Distance_To_Roadways  Hillshade_9am  Hillshade_Noon
1                              NaN            NaN             NaN
2                              NaN            NaN             NaN
3                              NaN            NaN             NaN
4                              NaN            NaN             NaN

   Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...  Soil_Type_32  \
0  Hillshade_3pm  Horizontal_Distance_To_Fire_Points  ...  Soil_Type_32
1            NaN                                 NaN  ...           NaN
2            NaN                                 NaN  ...           NaN
3            NaN                                 NaN  ...           NaN
4            NaN                                 NaN  ...           NaN

   Soil_Type_33  Soil_Type_34  Soil_Type_35  Soil_Type_36  Soil_Type_37  \
0  Soil_Type_33  Soil_Type_34  Soil_Type_35  Soil_Type_36  Soil_Type_37
1           NaN           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN           NaN
4           NaN           NaN           NaN           NaN           NaN

   Soil_Type_38  Soil_Type_39  Soil_Type_40  Cover_Type
0  Soil_Type_38  Soil_Type_39  Soil_Type_40  Cover_Type
1           NaN           NaN           NaN         NaN
2           NaN           NaN           NaN         NaN
3           NaN           NaN           NaN         NaN
4           NaN           NaN           NaN         NaN

[5 rows x 55 columns]

Valores ausentes por coluna:
Elevation                               0
Aspect                                175
Slope                                 241
Horizontal_Distance_To_Hydrology      247
Vertical_Distance_To_Hydrology        247
Horizontal_Distance_To_Roadways       247
Hillshade_9am                         247
Hillshade_Noon                        247
Hillshade_3pm                         247
Horizontal_Distance_To_Fire_Points    247
Wilderness_Area_1                     247
Wilderness_Area_2                     247
Wilderness_Area_3                     247
Wilderness_Area_4                     247
Soil_Type_1                           247
Soil_Type_2                           247
Soil_Type_3                           247
Soil_Type_4                           247
Soil_Type_5                           247
Soil_Type_6                           247
Soil_Type_7                           247
Soil_Type_8                           247
Soil_Type_9                           247
Soil_Type_10                          247
Soil_Type_11                          247
Soil_Type_12                          247
Soil_Type_13                          247
Soil_Type_14                          247
Soil_Type_15                          247
Soil_Type_16                          247
Soil_Type_17                          247
Soil_Type_18                          247
Soil_Type_19                          247
Soil_Type_20                          247
Soil_Type_21                          247
Soil_Type_22                          247
Soil_Type_23                          247
Soil_Type_24                          247
Soil_Type_25                          247
Soil_Type_26                          247
Soil_Type_27                          247
Soil_Type_28                          247
Soil_Type_29                          247
Soil_Type_30                          247
Soil_Type_31                          247
Soil_Type_32                          247
Soil_Type_33                          247
Soil_Type_34                          247
Soil_Type_35                          247
Soil_Type_36                          247
Soil_Type_37                          247
Soil_Type_38                          247
Soil_Type_39                          247
Soil_Type_40                          247
Cover_Type                            247
dtype: int64

Total de valores ausentes:
13260

TypeError: Cannot convert ['Elevation' 'The Forest CoverType dataset' '1.\tTitle of Database:'
 '\tForest Covertype data' '2.\tSources:'
 '\t(a) Original owners of database:' '\t\tRemote Sensing and GIS Program'
 '\t\tDepartment of Forest Sciences' '\t\tCollege of Natural Resources'
 '\t\tColorado State University' '\t\tFort Collins'
 '\t\t(contact Jock A. Blackard' '\t\t      or Dr. Denis J. Dean'
 '\tNOTE:\tReuse of this database is unlimited with retention of '
 '\t\tcopyright notice for Jock A. Blackard and Colorado '
 '\t\tState University.' '\t(b) Donors of database:'
 "\t\tJock A. Blackard (jblackard 'at' fs.fed.us)" '\t\tGIS Coordinator'
 '\t\tUSFS - Forest Inventory & Analysis'
 '\t\tRocky Mountain Research Station' '\t\t507 25th Street' '\t\tOgden'
 "\t\tDr. Denis J. Dean (denis.dean 'at' utdallas.edu)" '\t\tProfessor'
 '\t\tProgram in Geography and Geospatial Sciences'
 '\t\tSchool of Economic' '\t\t800 West Campbell Rd' '\t\tRichardson'
 "\t\tDr. Charles W. Anderson (anderson 'at' cs.colostate.edu)"
 '\t\tAssociate Professor' '\t\tDepartment of Computer Science'
 '\t\tColorado State University' '\t\tFort Collins'
 '\t(c) Date donated:  August 1998' '3.\tPast Usage:' '\tBlackard'
 '\t\tAccuracies of Artificial Neural Networks and Discriminant'
 '\t\tAnalysis in Predicting Forest Cover Types from Cartographic'
 '\t\tVariables."  Computers and Electronics in Agriculture '
 '\t\t24(3):131-151.' '\tBlackard'
 '\t\tAccuracies of Neural Networks and Discriminant Analysis'
 '\t\tin Predicting Forest Cover Types from Cartographic '
 '\t\tVariables."  Second Southern Forestry GIS Conference.'
 '\t\tUniversity of Georgia.  Athens' '\tBlackard'
 '\t\tDiscriminant Analysis in Predicting Forest Cover Types."'
 '\t\tPh.D. dissertation.  Department of Forest Sciences.  '
 '\t\tColorado State University.  Fort Collins' '\t\t165 pages.'
 '\tAbstract of dissertation:'
 '\t\tNatural resource managers responsible for developing '
 '\tecosystem management strategies require basic descriptive '
 '\tinformation including inventory data for forested lands to '
 '\tsupport their decision-making processes.  However'
 '\tgenerally do not have this type of data for inholdings or '
 '\tneighboring lands that are outside their immediate '
 '\tjurisdiction.  One method of obtaining this information is '
 '\tthrough the use of predictive models.  '
 '\t\tTwo predictive models were examined in this study'
 '\tfeedforward neural network model and a more traditional '
 '\tstatistical model based on discriminant analysis.  The overall '
 '\tobjectives of this research were to first construct these two '
 '\tpredictive models'
 '\trespective classification accuracies when predicting forest '
 '\tcover types in undisturbed forests.  '
 '\t\tThe study area included four wilderness areas found in '
 '\tthe Roosevelt National Forest of northern Colorado.  A total '
 '\tof twelve cartographic measures were utilized as independent '
 '\tvariables in the predictive models'
 '\tcover types were used as dependent variables.  Several subsets '
 '\tof these variables were examined to determine the best overall '
 '\tpredictive model.  '
 '\t\tFor each subset of cartographic variables examined in '
 '\tthis study' '\tneural network approach outperformed the traditional '
 '\tdiscriminant analysis method in predicting forest cover types.  '
 '\tThe final neural network model had a higher absolute '
 '\tclassification accuracy (70.58%) than the final corresponding '
 '\tlinear discriminant analysis model(58.38%).  In support of these '
 '\tclassification results'
 '\tselected initial weights were derived.  From these networks'
 '\toverall mean absolute classification accuracy for the neural '
 '\tnetwork method was 70.52%' '\t70.26% to 70.80%.  Consequently'
 '\tutilize an alternative method of predicting forest cover types '
 '\tthat is both superior to the traditional statistical methods and '
 '\tadequate to support their decision-making processes for '
 '\tdeveloping ecosystem management strategies.'
 '\t-- Classification performance' '\t\t-- first 11' '\t\t-- next 3'
 '\t\t-- last 565' '\t\t-- 70% Neural Network (backpropagation)'
 '\t\t-- 58% Linear Discriminant Analysis'
 '4.\tRelevant Information Paragraph:'
 '\tPredicting forest cover type from cartographic variables only'
 '\t(no remotely sensed data).  The actual forest cover type for'
 '\ta given observation (30 x 30 meter cell) was determined from'
 '\tUS Forest Service (USFS) Region 2 Resource Information System '
 '\t(RIS) data.  Independent variables were derived from data'
 '\toriginally obtained from US Geological Survey (USGS) and'
 '\tUSFS data.  Data is in raw form (not scaled) and contains'
 '\tbinary (0 or 1) columns of data for qualitative independent'
 '\tvariables (wilderness areas and soil types).'
 '\tThis study area includes four wilderness areas located in the'
 '\tRoosevelt National Forest of northern Colorado.  These areas'
 '\trepresent forests with minimal human-caused disturbances'
 '\tso that existing forest cover types are more a result of '
 '\tecological processes rather than forest management practices.'
 '\tSome background information for these four wilderness areas:  '
 '\tNeota (area 2) probably has the highest mean elevational value of '
 '\tthe 4 wilderness areas. Rawah (area 1) and Comanche Peak (area 3) '
 '\twould have a lower mean elevational value'
 '\t(area 4) would have the lowest mean elevational value. '
 '\tAs for primary major tree species in these areas'
 '\tspruce/fir (type 1)'
 '\thave lodgepole pine (type 2) as their primary species'
 '\tspruce/fir and aspen (type 5). Cache la Poudre would tend to have '
 '\tPonderosa pine (type 3)' '\tcottonwood/willow (type 4).  '
 '\tThe Rawah and Comanche Peak areas would tend to be more typical of '
 '\tthe overall dataset than either the Neota or Cache la Poudre'
 '\tto their assortment of tree species and range of predictive '
 '\tvariable values (elevation' '\tbe more unique than the others'
 '\televation range and species composition. '
 '5.\tNumber of instances (observations):  581'
 '6.\tNumber of Attributes:\t12 measures'
 '\t\t\t\t(10 quantitative variables'
 '\t\t\t\twilderness areas and 40 binary' '\t\t\t\tsoil type variables)'
 '7.\tAttribute information:' 'Given is the attribute name'
 'a brief description.  The forest cover type is the classification '
 'problem.  The order of this listing corresponds to the order of '
 'numerals along the rows of the database.'
 'Name                                     Data Type    Measurement                       Description'
 'Elevation                               quantitative    meters                       Elevation in meters'
 'Aspect                                  quantitative    azimuth                      Aspect in degrees azimuth'
 'Slope                                   quantitative    degrees                      Slope in degrees'
 'Horizontal_Distance_To_Hydrology        quantitative    meters                       Horz Dist to nearest surface water features'
 'Vertical_Distance_To_Hydrology          quantitative    meters                       Vert Dist to nearest surface water features'
 'Horizontal_Distance_To_Roadways         quantitative    meters                       Horz Dist to nearest roadway'
 'Hillshade_9am                           quantitative    0 to 255 index               Hillshade index at 9am'
 'Hillshade_Noon                          quantitative    0 to 255 index               Hillshade index at noon'
 'Hillshade_3pm                           quantitative    0 to 255 index               Hillshade index at 3pm'
 'Horizontal_Distance_To_Fire_Points      quantitative    meters                       Horz Dist to nearest wildfire ignition points'
 'Wilderness_Area (4 binary columns)      qualitative     0 (absence) or 1 (presence)  Wilderness area designation'
 'Soil_Type (40 binary columns)           qualitative     0 (absence) or 1 (presence)  Soil Type designation'
 'Cover_Type (7 types)                    integer         1 to 7                       Forest Cover Type designation'
 'Code Designations:' 'Wilderness Areas:  \t1 -- Rawah Wilderness Area'
 '                        2 -- Neota Wilderness Area'
 '                        3 -- Comanche Peak Wilderness Area'
 '                        4 -- Cache la Poudre Wilderness Area'
 'Soil Types:             1 to 40 : based on the USFS Ecological'
 '                        Landtype Units (ELUs) for this study area:'
 '  Study Code USFS ELU Code\t\t\tDescription'
 '\t 1\t   2702\t\tCathedral family - Rock outcrop complex'
 '\t 2\t   2703\t\tVanet - Ratake families complex'
 '\t 3\t   2704\t\tHaploborolis - Rock outcrop complex'
 '\t 4\t   2705\t\tRatake family - Rock outcrop complex'
 '\t 5\t   2706\t\tVanet family - Rock outcrop complex complex'
 '\t 6\t   2717\t\tVanet - Wetmore families - Rock outcrop complex'
 '\t 7\t   3501\t\tGothic family.'
 '\t 8\t   3502\t\tSupervisor - Limber families complex.'
 '\t 9\t   4201\t\tTroutville family'
 '\t10\t   4703\t\tBullwark - Catamount families - Rock outcrop complex'
 '\t11\t   4704\t\tBullwark - Catamount families - Rock land complex'
 '\t12\t   4744\t\tLegault family - Rock land complex'
 '\t13\t   4758\t\tCatamount family - Rock land - Bullwark family complex'
 '\t14\t   5101\t\tPachic Argiborolis - Aquolis complex.'
 '\t15\t   5151\t\tunspecified in the USFS Soil and ELU Survey.'
 '\t16\t   6101\t\tCryaquolis - Cryoborolis complex.'
 '\t17\t   6102\t\tGateview family - Cryaquolis complex.'
 '\t18\t   6731\t\tRogert family'
 '\t19\t   7101\t\tTypic Cryaquolis - Borohemists complex.'
 '\t20\t   7102\t\tTypic Cryaquepts - Typic Cryaquolls complex.'
 '\t21\t   7103\t\tTypic Cryaquolls - Leighcan family'
 '\t22\t   7201\t\tLeighcan family' '\t23\t   7202\t\tLeighcan family'
 '\t24\t   7700\t\tLeighcan family' '\t25\t   7701\t\tLeighcan family'
 '\t26\t   7702\t\tGranile - Catamount families complex'
 '\t27\t   7709\t\tLeighcan family'
 '\t28\t   7710\t\tLeighcan family - Rock outcrop complex'
 '\t29\t   7745\t\tComo - Legault families complex'
 '\t30\t   7746\t\tComo family - Rock land - Legault family complex'
 '\t31\t   7755\t\tLeighcan - Catamount families complex'
 '\t32\t   7756\t\tCatamount family - Rock outcrop - Leighcan family complex'
 '\t33\t   7757\t\tLeighcan - Catamount families - Rock outcrop complex'
 '\t34\t   7790\t\tCryorthents - Rock land complex'
 '\t35\t   8703\t\tCryumbrepts - Rock outcrop - Cryaquepts complex.'
 '\t36\t   8707\t\tBross family - Rock land - Cryumbrepts complex'
 '\t37\t   8708\t\tRock outcrop - Cryumbrepts - Cryorthents complex'
 '\t38\t   8771\t\tLeighcan - Moran families - Cryaquolls complex'
 '\t39\t   8772\t\tMoran family - Cryorthents - Leighcan family complex'
 '\t40\t   8776\t\tMoran family - Cryorthents - Rock land complex'
 '        Note:   First digit:  climatic zone             Second digit:  geologic zones'
 '                1.  lower montane dry                   1.  alluvium'
 '                2.  lower montane                       2.  glacial'
 '                3.  montane dry                         3.  shale'
 '                4.  montane                             4.  sandstone'
 '                5.  montane dry and montane             5.  mixed sedimentary'
 '                6.  montane and subalpine               6.  unspecified in the USFS ELU Survey'
 '                7.  subalpine                           7.  igneous and metamorphic'
 '                8.  alpine                              8.  volcanic'
 '        The third and fourth ELU digits are unique to the mapping unit '
 '        and have no special meaning to the climatic or geologic zones.'
 'Forest Cover Type Classes:\t1 -- Spruce/Fir'
 '                                2 -- Lodgepole Pine'
 '                                3 -- Ponderosa Pine'
 '                                4 -- Cottonwood/Willow'
 '                                5 -- Aspen'
 '                                6 -- Douglas-fir'
 '                                7 -- Krummholz'
 '8.  Basic Summary Statistics for quantitative variables only'
 '\t(whole dataset -- thanks to Phil Rennert for the summary values):'
 'Name                                    Units             Mean   Std Dev'
 'Elevation                               meters          2959.36  279.98'
 'Aspect                                  azimuth          155.65  111.91'
 'Slope                                   degrees           14.10    7.49'
 'Horizontal_Distance_To_Hydrology        meters           269.43  212.55'
 'Vertical_Distance_To_Hydrology          meters            46.42   58.30'
 'Horizontal_Distance_To_Roadways         meters          2350.15 1559.25'
 'Hillshade_9am                           0 to 255 index   212.15   26.77'
 'Hillshade_Noon                          0 to 255 index   223.32   19.77'
 'Hillshade_3pm                           0 to 255 index   142.53   38.27'
 'Horizontal_Distance_To_Fire_Points      meters          1980.29 1324.19'
 '9.\tMissing Attribute Values:  None.' '10.\tClass distribution:'
 '           Number of records of Spruce-Fir:                211840 '
 '           Number of records of Lodgepole Pine:            283301 '
 '           Number of records of Ponderosa Pine:             35754 '
 '           Number of records of Cottonwood/Willow:           2747 '
 '           Number of records of Aspen:                       9493 '
 '           Number of records of Douglas-fir:                17367 '
 '           Number of records of Krummholz:                  20510  '
 '           Number of records of other:                          0  '
 '           Total records:                                  581012'
 '====================================================================='
 'Jock A. Blackard' '08/28/1998 -- original text'
 '12/07/1999 -- updated mailing address' '\t\t  for study area'
 '====================================================================='] to numeric

In [ ]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score

In [ ]:
import pandas as pd

# Carrega o dataset de treino JÁ PRÉ-PROCESSADO, que foi salvo como 'covtype_tratado.csv'
df = pd.read_csv('covtype_tratado.csv')

print("DataFrame 'df' carregado com sucesso a partir de 'covtype_tratado.csv'.")

FileNotFoundError: [Errno 2] No such file or directory: 'covtype_tratado.csv'

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Separar atributos (X) e classe (y)
X = df.drop("Cover_Type", axis=1)
y = df["Cover_Type"]

# Dividir os dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Classificador simples - baseline
modelo = DecisionTreeClassifier(random_state=42)

# Treinar
modelo.fit(X_train, y_train)

# Fazer previsões
y_pred = modelo.predict(X_test)

# Avaliar
acuracia = accuracy_score(y_test, y_pred)

print("Acurácia do baseline:", acuracia)

NameError: name 'df' is not defined

In [ ]:
from google.colab import files

arquivo = files.upload()

Saving covtype.csv to covtype.csv

In [ ]:
import pandas as pd

df = pd.read_csv("covtype.csv")

In [ ]:
print(df.shape)
df.head()

(247, 55)

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Soil_Type_40,Cover_Type
0,The Forest CoverType dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.\tTitle of Database:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,\tForest Covertype data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.\tSources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,\t(a) Original owners of database:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology',
       'Vertical_Distance_To_Hydrology', 'Horizontal_Distance_To_Roadways',
       'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points', 'Wilderness_Area_1',
       'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4',
       'Soil_Type_1', 'Soil_Type_2', 'Soil_Type_3', 'Soil_Type_4',
       'Soil_Type_5', 'Soil_Type_6', 'Soil_Type_7', 'Soil_Type_8',
       'Soil_Type_9', 'Soil_Type_10', 'Soil_Type_11', 'Soil_Type_12',
       'Soil_Type_13', 'Soil_Type_14', 'Soil_Type_15', 'Soil_Type_16',
       'Soil_Type_17', 'Soil_Type_18', 'Soil_Type_19', 'Soil_Type_20',
       'Soil_Type_21', 'Soil_Type_22', 'Soil_Type_23', 'Soil_Type_24',
       'Soil_Type_25', 'Soil_Type_26', 'Soil_Type_27', 'Soil_Type_28',
       'Soil_Type_29', 'Soil_Type_30', 'Soil_Type_31', 'Soil_Type_32',
       'Soil_Type_33', 'Soil_Type_34', 'Soil_Type_35', 'Soil_Type_36',
       'Soil_Type_37', 'Soil_Type_38', 'Soil_Type_39', 'Soil_Type_40',
       'Cover_Type'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 55 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Elevation                           247 non-null    object
 1   Aspect                              72 non-null     object
 2   Slope                               6 non-null      object
 3   Horizontal_Distance_To_Hydrology    0 non-null      float64
 4   Vertical_Distance_To_Hydrology      0 non-null      float64
 5   Horizontal_Distance_To_Roadways     0 non-null      float64
 6   Hillshade_9am                       0 non-null      float64
 7   Hillshade_Noon                      0 non-null      float64
 8   Hillshade_3pm                       0 non-null      float64
 9   Horizontal_Distance_To_Fire_Points  0 non-null      float64
 10  Wilderness_Area_1                   0 non-null      float64
 11  Wilderness_Area_2                   0 non-null      float64
 12  Wilderness_Area_3                   0 non-null      float64
 13  Wilderness_Area_4                   0 non-null      float64
 14  Soil_Type_1                         0 non-null      float64
 15  Soil_Type_2                         0 non-null      float64
 16  Soil_Type_3                         0 non-null      float64
 17  Soil_Type_4                         0 non-null      float64
 18  Soil_Type_5                         0 non-null      float64
 19  Soil_Type_6                         0 non-null      float64
 20  Soil_Type_7                         0 non-null      float64
 21  Soil_Type_8                         0 non-null      float64
 22  Soil_Type_9                         0 non-null      float64
 23  Soil_Type_10                        0 non-null      float64
 24  Soil_Type_11                        0 non-null      float64
 25  Soil_Type_12                        0 non-null      float64
 26  Soil_Type_13                        0 non-null      float64
 27  Soil_Type_14                        0 non-null      float64
 28  Soil_Type_15                        0 non-null      float64
 29  Soil_Type_16                        0 non-null      float64
 30  Soil_Type_17                        0 non-null      float64
 31  Soil_Type_18                        0 non-null      float64
 32  Soil_Type_19                        0 non-null      float64
 33  Soil_Type_20                        0 non-null      float64
 34  Soil_Type_21                        0 non-null      float64
 35  Soil_Type_22                        0 non-null      float64
 36  Soil_Type_23                        0 non-null      float64
 37  Soil_Type_24                        0 non-null      float64
 38  Soil_Type_25                        0 non-null      float64
 39  Soil_Type_26                        0 non-null      float64
 40  Soil_Type_27                        0 non-null      float64
 41  Soil_Type_28                        0 non-null      float64
 42  Soil_Type_29                        0 non-null      float64
 43  Soil_Type_30                        0 non-null      float64
 44  Soil_Type_31                        0 non-null      float64
 45  Soil_Type_32                        0 non-null      float64
 46  Soil_Type_33                        0 non-null      float64
 47  Soil_Type_34                        0 non-null      float64
 48  Soil_Type_35                        0 non-null      float64
 49  Soil_Type_36                        0 non-null      float64
 50  Soil_Type_37                        0 non-null      float64
 51  Soil_Type_38                        0 non-null      float64
 52  Soil_Type_39                        0 non-null      float64
 53  Soil_Type_40                        0 non-null      float64
 54  Cover_Type                          0 non-null      float64
dtypes: float64(52), object(3)
memory usage: 106.3+ KB

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Separar entradas (X) e classe alvo (y)
# CORREÇÃO: O nome correto da coluna é 'Cover_Type', não 'covertype'
X = df.drop("Cover_Type", axis=1)
y = df["Cover_Type"]

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Criar o classificador mais simples
modelo = DecisionTreeClassifier(random_state=42)

# Treinar
modelo.fit(X_train, y_train)

# Prever
y_pred = modelo.predict(X_test)

# Avaliar
print("Acurácia:", accuracy_score(y_test, y_pred))

KeyError: "['covertype'] not found in axis"

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Separar entradas (X) e classe alvo (y)
X = df.drop("Cover_Type", axis=1)
y = df["Cover_Type"]

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Criar o classificador mais simples
modelo = DecisionTreeClassifier(random_state=42)

# Treinar
modelo.fit(X_train, y_train)

# Prever
y_pred = modelo.predict(X_test)

# Avaliar
print("Acurácia:", accuracy_score(y_test, y_pred))

ValueError: could not convert string to float: '                        3 -- Comanche Peak Wilderness Area'

In [ ]:
"""
Baseline mais simples possível para o dataset Forest CoverType.

O baseline mais simples de todos, em classificação, é um classificador
"burro" (DummyClassifier) que sempre prevê a classe mais frequente do
treino. Qualquer modelo real (regressão logística, árvore, etc.) só faz
sentido se conseguir superar esse número.

Uso:
    python baseline_covtype.py caminho/para/covtype.csv
"""

import sys
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier
from sklearn.metrics import accuracy_score, classification_report

TARGET_COL = "Cover_Type"


def main(csv_path: str):
    # 1. Carregar os dados
    df = pd.read_csv(csv_path)

    if TARGET_COL not in df.columns:
        raise ValueError(
            f"Coluna alvo '{TARGET_COL}' não encontrada. "
            f"Colunas disponíveis: {list(df.columns)}"
        )

    X = df.drop(columns=[TARGET_COL])
    y = df[TARGET_COL]

    # 2. Separar treino/teste
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    # 3. Treinar o baseline (classe mais frequente)
    baseline = DummyClassifier(strategy="most_frequent")
    baseline.fit(X_train, y_train)

    # 4. Avaliar
    y_pred = baseline.predict(X_test)
    acc = accuracy_score(y_test, y_pred)

    print(f"Linhas usadas: {len(df)}")
    print(f"Acurácia do baseline (most_frequent): {acc:.4f}")
    print()
    print(classification_report(y_test, y_pred, zero_division=0))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Uso: python baseline_covtype.py caminho/para/covtype.csv")
        sys.exit(1)
    main(sys.argv[1])

Uso: python baseline_covtype.py caminho/para/covtype.csv

SystemExit: 1

/usr/local/lib/python3.13/dist-packages/IPython/core/interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)